<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>cbb87819-b155-40a0-a9fc-9429a307a96e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
    set 'the gender' to "Male" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
