<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>fdf6002a-7ea2-4cab-acdb-6247a2b10a19</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
    set 'the hour' to 10 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
