<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ff71e10f-887f-4efe-849b-7d2b39c815f3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to " We don't have correct information to greet you!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
