<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>edf4bcfc-cf1e-4a6e-9504-b93d3adda028</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'the name' to "Jones" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
